import { ElementState, Category, FLAGS } from './constants';
import { Element } from './types';

let elementId = 0;

const nextId = () => ++elementId;

export const elements: Record<string, Element> = {
  EMPTY: {
    id: 0,
    name: 'Empty',
    nameCn: '空气',
    symbol: 'AIR',
    color: '#000000',
    density: 0,
    state: ElementState.GAS,
    category: Category.GAS,
    flammability: 0,
    conductivity: 0,
    hardness: 0,
    diffusion: 0,
    flags: 0,
    description: '空',
  },

  Sand: {
    id: nextId(),
    name: 'Sand',
    nameCn: '沙子',
    symbol: 'SAND',
    color: '#e6c87a',
    colors: ['#e6c87a', '#d4b566', '#f0d88a'],
    density: 3,
    state: ElementState.POWDER,
    category: Category.POWDER,
    meltingPoint: 1973,
    boilingPoint: 2500,
    flammability: 0,
    conductivity: 0,
    hardness: 2,
    flags: 0,
    description: '沙子，可以被风吹动',
  },

  Salt: {
    id: nextId(),
    name: 'Salt',
    nameCn: '盐',
    symbol: 'SALT',
    color: '#f0f0f0',
    colors: ['#f0f0f0', '#e8e8e8', '#ffffff'],
    density: 2.5,
    state: ElementState.POWDER,
    category: Category.POWDER,
    meltingPoint: 1074,
    boilingPoint: 1686,
    flammability: 0,
    conductivity: 1,
    hardness: 2,
    flags: FLAGS.CONDUCTIVE,
    description: '盐，可以溶于水',
  },

  Gunpowder: {
    id: nextId(),
    name: 'Gunpowder',
    nameCn: '火药',
    symbol: 'GUNP',
    color: '#808080',
    colors: ['#606060', '#808080', '#a0a0a0'],
    density: 2,
    state: ElementState.POWDER,
    category: Category.POWDER,
    flammability: 10,
    conductivity: 0,
    hardness: 1,
    flags: FLAGS.FLAMMABLE,
    description: '火药，遇火会爆炸',
  },

  Snow: {
    id: nextId(),
    name: 'Snow',
    nameCn: '雪',
    symbol: 'SNOW',
    color: '#ffffff',
    colors: ['#ffffff', '#f0f8ff', '#e6f3ff'],
    density: 0.5,
    state: ElementState.POWDER,
    category: Category.POWDER,
    meltingPoint: 273,
    boilingPoint: 373,
    flammability: 0,
    conductivity: 0,
    hardness: 0,
    flags: FLAGS.COLD,
    description: '雪，遇热融化成水',
  },

  Dust: {
    id: nextId(),
    name: 'Dust',
    nameCn: '灰尘',
    symbol: 'DUST',
    color: '#c4a484',
    colors: ['#b8956e', '#c4a484', '#d4b896'],
    density: 0.3,
    state: ElementState.POWDER,
    category: Category.POWDER,
    flammability: 2,
    conductivity: 0,
    hardness: 0,
    diffusion: 0.1,
    flags: 0,
    description: '灰尘，可以漂浮',
  },

  Ash: {
    id: nextId(),
    name: 'Ash',
    nameCn: '灰烬',
    symbol: 'ASH',
    color: '#505050',
    colors: ['#404040', '#505050', '#606060'],
    density: 0.8,
    state: ElementState.POWDER,
    category: Category.POWDER,
    flammability: 0,
    conductivity: 0,
    hardness: 0,
    diffusion: 0.05,
    flags: FLAGS.HOT,
    description: '灰烬，燃烧后的产物',
  },

  Coal: {
    id: nextId(),
    name: 'Coal',
    nameCn: '煤粉',
    symbol: 'COAL',
    color: '#2a2a2a',
    colors: ['#1a1a1a', '#2a2a2a', '#3a3a3a'],
    density: 2.2,
    state: ElementState.POWDER,
    category: Category.POWDER,
    flammability: 8,
    conductivity: 1,
    hardness: 2,
    flags: FLAGS.FLAMMABLE | FLAGS.CONDUCTIVE,
    description: '煤粉，可以燃烧很长时间',
  },

  Cement: {
    id: nextId(),
    name: 'Cement',
    nameCn: '水泥',
    symbol: 'CMNT',
    color: '#a0a0a0',
    colors: ['#909090', '#a0a0a0', '#b0b0b0'],
    density: 2.8,
    state: ElementState.POWDER,
    category: Category.POWDER,
    flammability: 0,
    conductivity: 0,
    hardness: 1,
    flags: 0,
    description: '水泥，遇水会凝固',
  },

  H2O: {
    id: nextId(),
    name: 'H2O',
    nameCn: '水',
    symbol: 'H2O',
    color: '#4080c0',
    colors: ['#3070b0', '#4080c0', '#5090d0'],
    density: 1,
    state: ElementState.LIQUID,
    category: Category.LIQUID,
    meltingPoint: 273,
    boilingPoint: 373,
    flammability: 0,
    conductivity: 2,
    hardness: 0,
    viscosity: 1,
    diffusion: 1,
    flags: FLAGS.CONDUCTIVE,
    description: '水，生命之源',
  },

  Oil: {
    id: nextId(),
    name: 'Oil',
    nameCn: '油',
    symbol: 'OIL',
    color: '#604020',
    colors: ['#503010', '#604020', '#705030'],
    density: 0.8,
    state: ElementState.LIQUID,
    category: Category.LIQUID,
    meltingPoint: 250,
    boilingPoint: 600,
    flammability: 9,
    conductivity: 0,
    hardness: 0,
    viscosity: 2,
    diffusion: 0.5,
    flags: FLAGS.FLAMMABLE,
    description: '油，可以漂浮在水面上燃烧',
  },

  Lava: {
    id: nextId(),
    name: 'Lava',
    nameCn: '岩浆',
    symbol: 'LAVA',
    color: '#ff4000',
    colors: ['#ff3000', '#ff5000', '#ff6020'],
    density: 4,
    state: ElementState.LIQUID,
    category: Category.LIQUID,
    boilingPoint: 1500,
    flammability: 0,
    conductivity: 5,
    hardness: 1,
    viscosity: 4,
    flags: FLAGS.HOT | FLAGS.GLOWING | FLAGS.CONDUCTIVE,
    description: '岩浆，高温液体，可以点燃可燃物',
  },

  Acid: {
    id: nextId(),
    name: 'Acid',
    nameCn: '酸',
    symbol: 'ACID',
    color: '#80ff40',
    colors: ['#70ff30', '#80ff40', '#90ff50'],
    density: 1.2,
    state: ElementState.LIQUID,
    category: Category.LIQUID,
    flammability: 1,
    conductivity: 3,
    hardness: 0,
    viscosity: 1,
    diffusion: 1,
    flags: FLAGS.CONDUCTIVE,
    description: '酸，可以腐蚀大多数物质',
  },

  LN2: {
    id: nextId(),
    name: 'LN2',
    nameCn: '液氮',
    symbol: 'LN2',
    color: '#80c0ff',
    colors: ['#70b0ff', '#80c0ff', '#90d0ff'],
    density: 0.9,
    state: ElementState.LIQUID,
    category: Category.LIQUID,
    boilingPoint: 77,
    flammability: 0,
    conductivity: 0,
    hardness: 0,
    viscosity: 0.5,
    diffusion: 2,
    flags: FLAGS.COLD,
    description: '液氮，极低温液体，会快速气化',
  },

  Mercury: {
    id: nextId(),
    name: 'Mercury',
    nameCn: '水银',
    symbol: 'HG',
    color: '#c0c0c0',
    colors: ['#b0b0b0', '#c0c0c0', '#d0d0d0'],
    density: 13.5,
    state: ElementState.LIQUID,
    category: Category.LIQUID,
    meltingPoint: 234,
    boilingPoint: 630,
    flammability: 0,
    conductivity: 8,
    hardness: 0,
    viscosity: 3,
    flags: FLAGS.CONDUCTIVE,
    description: '水银，重金属液体，导电',
  },

  Alcohol: {
    id: nextId(),
    name: 'Alcohol',
    nameCn: '酒精',
    symbol: 'ALCH',
    color: '#ffc080',
    colors: ['#ffb070', '#ffc080', '#ffd090'],
    density: 0.79,
    state: ElementState.LIQUID,
    category: Category.LIQUID,
    meltingPoint: 159,
    boilingPoint: 351,
    flammability: 10,
    conductivity: 0,
    hardness: 0,
    viscosity: 0.5,
    diffusion: 1.5,
    flags: FLAGS.FLAMMABLE,
    description: '酒精，极易燃烧',
  },

  Steam: {
    id: nextId(),
    name: 'Steam',
    nameCn: '水蒸气',
    symbol: 'STMC',
    color: '#c0e0ff',
    colors: ['#b0d0ff', '#c0e0ff', '#d0f0ff'],
    density: -0.5,
    state: ElementState.GAS,
    category: Category.GAS,
    flammability: 0,
    conductivity: 0,
    hardness: 0,
    diffusion: 3,
    life: 500,
    flags: FLAGS.HOT,
    description: '水蒸气，水沸腾产生',
  },

  Smoke: {
    id: nextId(),
    name: 'Smoke',
    nameCn: '烟',
    symbol: 'SMKE',
    color: '#606060',
    colors: ['#505050', '#606060', '#707070'],
    density: -0.3,
    state: ElementState.GAS,
    category: Category.GAS,
    flammability: 0,
    conductivity: 0,
    hardness: 0,
    diffusion: 2,
    life: 800,
    flags: 0,
    description: '烟，燃烧产生',
  },

  O2: {
    id: nextId(),
    name: 'O2',
    nameCn: '氧气',
    symbol: 'O2',
    color: '#80a0ff',
    colors: ['#7090ff', '#80a0ff', '#90b0ff'],
    density: -1,
    state: ElementState.GAS,
    category: Category.GAS,
    flammability: 0,
    conductivity: 0,
    hardness: 0,
    diffusion: 4,
    flags: 0,
    description: '氧气，助燃气体',
  },

  H2: {
    id: nextId(),
    name: 'H2',
    nameCn: '氢气',
    symbol: 'H2',
    color: '#e0e0ff',
    colors: ['#d0d0ff', '#e0e0ff', '#f0f0ff'],
    density: -2,
    state: ElementState.GAS,
    category: Category.GAS,
    flammability: 10,
    conductivity: 0,
    hardness: 0,
    diffusion: 5,
    flags: FLAGS.FLAMMABLE,
    description: '氢气，极易燃气体',
  },

  CO2: {
    id: nextId(),
    name: 'CO2',
    nameCn: '二氧化碳',
    symbol: 'CO2',
    color: '#a0a0a0',
    colors: ['#909090', '#a0a0a0', '#b0b0b0'],
    density: 0.5,
    state: ElementState.GAS,
    category: Category.GAS,
    flammability: 0,
    conductivity: 0,
    hardness: 0,
    diffusion: 2,
    flags: 0,
    description: '二氧化碳，可以灭火',
  },

  Plasma: {
    id: nextId(),
    name: 'Plasma',
    nameCn: '等离子体',
    symbol: 'PLSM',
    color: '#ff80ff',
    colors: ['#ff70ff', '#ff80ff', '#ff90ff'],
    density: -1.5,
    state: ElementState.GAS,
    category: Category.GAS,
    flammability: 0,
    conductivity: 10,
    hardness: 0,
    diffusion: 3,
    life: 200,
    flags: FLAGS.HOT | FLAGS.GLOWING | FLAGS.CONDUCTIVE,
    description: '等离子体，高温电离气体',
  },

  Cold: {
    id: nextId(),
    name: 'Cold',
    nameCn: '冷气',
    symbol: 'COLD',
    color: '#a0e0ff',
    colors: ['#90d0ff', '#a0e0ff', '#b0f0ff'],
    density: -0.2,
    state: ElementState.GAS,
    category: Category.GAS,
    flammability: 0,
    conductivity: 0,
    hardness: 0,
    diffusion: 2,
    life: 300,
    flags: FLAGS.COLD,
    description: '冷气，可以冷却物体',
  },

  Wall: {
    id: nextId(),
    name: 'Wall',
    nameCn: '墙',
    symbol: 'WALL',
    color: '#808080',
    colors: ['#707070', '#808080', '#909090'],
    density: 100,
    state: ElementState.SOLID,
    category: Category.SOLID,
    flammability: 0,
    conductivity: 0,
    hardness: 100,
    flags: FLAGS.STATIC | FLAGS.INDESTRUCTIBLE,
    description: '不可摧毁的墙',
  },

  Stone: {
    id: nextId(),
    name: 'Stone',
    nameCn: '石头',
    symbol: 'STNE',
    color: '#808080',
    colors: ['#707070', '#808080', '#909090'],
    density: 5,
    state: ElementState.SOLID,
    category: Category.SOLID,
    meltingPoint: 1500,
    boilingPoint: 2800,
    flammability: 0,
    conductivity: 2,
    hardness: 8,
    flags: FLAGS.STATIC | FLAGS.CONDUCTIVE,
    description: '石头，可以被酸腐蚀',
  },

  Metal: {
    id: nextId(),
    name: 'Metal',
    nameCn: '金属',
    symbol: 'METL',
    color: '#c0c0c0',
    colors: ['#b0b0b0', '#c0c0c0', '#d0d0d0'],
    density: 8,
    state: ElementState.SOLID,
    category: Category.SOLID,
    meltingPoint: 1800,
    boilingPoint: 3000,
    flammability: 0,
    conductivity: 10,
    hardness: 7,
    flags: FLAGS.STATIC | FLAGS.CONDUCTIVE,
    description: '金属，导电，可以被熔化',
  },

  Glass: {
    id: nextId(),
    name: 'Glass',
    nameCn: '玻璃',
    symbol: 'GLAS',
    color: '#a0d0e0',
    colors: ['#90c0d0', '#a0d0e0', '#b0e0f0'],
    density: 2.5,
    state: ElementState.SOLID,
    category: Category.SOLID,
    meltingPoint: 1700,
    boilingPoint: 2500,
    flammability: 0,
    conductivity: 0,
    hardness: 5,
    flags: FLAGS.STATIC,
    description: '玻璃，透明，可以熔化',
  },

  Wood: {
    id: nextId(),
    name: 'Wood',
    nameCn: '木头',
    symbol: 'WOOD',
    color: '#8b4513',
    colors: ['#7a3a10', '#8b4513', '#9c5524'],
    density: 1.5,
    state: ElementState.SOLID,
    category: Category.SOLID,
    flammability: 7,
    conductivity: 0,
    hardness: 4,
    flags: FLAGS.STATIC | FLAGS.FLAMMABLE,
    description: '木头，可以燃烧',
  },

  Ice: {
    id: nextId(),
    name: 'Ice',
    nameCn: '冰',
    symbol: 'ICE',
    color: '#a0d8ff',
    colors: ['#90c8ff', '#a0d8ff', '#b0e8ff'],
    density: 0.92,
    state: ElementState.SOLID,
    category: Category.SOLID,
    meltingPoint: 273,
    boilingPoint: 373,
    flammability: 0,
    conductivity: 1,
    hardness: 3,
    flags: FLAGS.STATIC | FLAGS.COLD | FLAGS.CONDUCTIVE,
    description: '冰，遇热融化成水',
  },

  Concrete: {
    id: nextId(),
    name: 'Concrete',
    nameCn: '混凝土',
    symbol: 'CNCR',
    color: '#909090',
    colors: ['#808080', '#909090', '#a0a0a0'],
    density: 4,
    state: ElementState.SOLID,
    category: Category.SOLID,
    flammability: 0,
    conductivity: 1,
    hardness: 9,
    flags: FLAGS.STATIC | FLAGS.CONDUCTIVE,
    description: '混凝土，非常坚硬',
  },

  Plant: {
    id: nextId(),
    name: 'Plant',
    nameCn: '植物',
    symbol: 'PLNT',
    color: '#40a040',
    colors: ['#309030', '#40a040', '#50b050'],
    density: 1,
    state: ElementState.SOLID,
    category: Category.SOLID,
    flammability: 6,
    conductivity: 0,
    hardness: 1,
    flags: FLAGS.FLAMMABLE | FLAGS.LIFE,
    description: '植物，可以生长',
  },

  Fire: {
    id: nextId(),
    name: 'Fire',
    nameCn: '火',
    symbol: 'FIRE',
    color: '#ff6000',
    colors: ['#ff4000', '#ff6000', '#ff8020', '#ffff00'],
    density: -0.8,
    state: ElementState.ENERGY,
    category: Category.ENERGY,
    flammability: 0,
    conductivity: 3,
    hardness: 0,
    diffusion: 1,
    life: 80,
    flags: FLAGS.HOT | FLAGS.GLOWING,
    description: '火，可以点燃可燃物',
  },

  Spark: {
    id: nextId(),
    name: 'Spark',
    nameCn: '电',
    symbol: 'SPRK',
    color: '#ffff00',
    colors: ['#ffff00', '#ffff80', '#ffffff'],
    density: 0,
    state: ElementState.ENERGY,
    category: Category.ENERGY,
    flammability: 8,
    conductivity: 10,
    hardness: 0,
    life: 30,
    flags: FLAGS.HOT | FLAGS.GLOWING | FLAGS.CONDUCTIVE,
    description: '电火花，可以导电和点燃',
  },

  Photon: {
    id: nextId(),
    name: 'Photon',
    nameCn: '光子',
    symbol: 'PHOT',
    color: '#ffffff',
    colors: ['#ffffff', '#ffff80', '#80ffff', '#ff80ff'],
    density: 0,
    state: ElementState.ENERGY,
    category: Category.ENERGY,
    flammability: 0,
    conductivity: 0,
    hardness: 0,
    life: 1000,
    flags: FLAGS.GLOWING,
    description: '光子，可以沿直线传播',
  },

  Heat: {
    id: nextId(),
    name: 'Heat',
    nameCn: '热源',
    symbol: 'HEAT',
    color: '#ff4040',
    colors: ['#ff3030', '#ff4040', '#ff5050'],
    density: -0.5,
    state: ElementState.ENERGY,
    category: Category.ENERGY,
    flammability: 0,
    conductivity: 0,
    hardness: 0,
    diffusion: 2,
    life: 200,
    flags: FLAGS.HOT | FLAGS.GLOWING | FLAGS.INDESTRUCTIBLE,
    description: '热源，持续产生热量',
  },

  Void: {
    id: nextId(),
    name: 'Void',
    nameCn: '虚空',
    symbol: 'VOID',
    color: '#200030',
    colors: ['#100020', '#200030', '#300040'],
    density: 100,
    state: ElementState.SOLID,
    category: Category.ENERGY,
    flammability: 0,
    conductivity: 0,
    hardness: 100,
    flags: FLAGS.STATIC | FLAGS.INDESTRUCTIBLE,
    description: '虚空，可以吞噬一切物质',
  },

  Eraser: {
    id: nextId(),
    name: 'Eraser',
    nameCn: '橡皮擦',
    symbol: 'ERAS',
    color: '#ff80c0',
    colors: ['#ff70b0', '#ff80c0', '#ff90d0'],
    density: 0,
    state: ElementState.SOLID,
    category: Category.SPECIAL,
    flammability: 0,
    conductivity: 0,
    hardness: 100,
    flags: FLAGS.INDESTRUCTIBLE,
    description: '橡皮擦，可以清除物质',
  },

  Cloner: {
    id: nextId(),
    name: 'Cloner',
    nameCn: '克隆器',
    symbol: 'CLNE',
    color: '#80ff80',
    colors: ['#70ff70', '#80ff80', '#90ff90'],
    density: 100,
    state: ElementState.SOLID,
    category: Category.SPECIAL,
    flammability: 0,
    conductivity: 0,
    hardness: 100,
    flags: FLAGS.STATIC | FLAGS.INDESTRUCTIBLE,
    description: '克隆器，可以复制接触到的物质',
  },
};

export const ELEMENT_COUNT = Object.keys(elements).length;

export const getElementById = (id: number): Element | undefined => {
  return Object.values(elements).find(el => el.id === id);
};

export const getElementByName = (name: string): Element | undefined => {
  return elements[name];
};
