import type { ElementCategory, ElementDefinition, ToolId } from "./types";

export enum ElementId {
  Empty = 0,
  Wall = 1,
  Stone = 2,
  Glass = 3,
  Wood = 4,
  Ice = 5,
  Metal = 6,
  Copper = 7,
  Gold = 8,
  Wire = 9,
  Battery = 10,
  Semiconductor = 11,
  Sand = 12,
  Dust = 13,
  Salt = 14,
  Coal = 15,
  Clay = 16,
  Water = 17,
  SaltWater = 18,
  Oil = 19,
  Acid = 20,
  Base = 21,
  Lava = 22,
  LiquidNitrogen = 23,
  Mercury = 24,
  Steam = 25,
  Smoke = 26,
  Hydrogen = 27,
  Oxygen = 28,
  Fire = 29,
  Plasma = 30,
  Spark = 31,
  Plant = 32,
  Seed = 33,
  Uranium = 34,
  Neutron = 35,
  Photon = 36,
  BlackHole = 37
}

const def = (definition: ElementDefinition): ElementDefinition => definition;

export const ELEMENTS: Record<ElementId, ElementDefinition> = {
  [ElementId.Empty]: def({
    id: ElementId.Empty,
    key: "empty",
    symbol: "VOID",
    name: "空",
    category: "solid",
    state: "empty",
    color: "#05070a",
    density: 0,
    heatCapacity: 1,
    conductivity: 0.04,
    acidResistance: 1
  }),
  [ElementId.Wall]: def({
    id: ElementId.Wall,
    key: "wall",
    symbol: "WALL",
    name: "墙",
    category: "solid",
    state: "solid",
    color: "#737987",
    density: 9999,
    heatCapacity: 5,
    conductivity: 0.2,
    acidResistance: 1,
    immovable: true
  }),
  [ElementId.Stone]: def({
    id: ElementId.Stone,
    key: "stone",
    symbol: "STNE",
    name: "石头",
    category: "solid",
    state: "solid",
    color: "#8b857b",
    density: 2600,
    heatCapacity: 4,
    conductivity: 0.18,
    acidResistance: 0.82,
    meltPoint: 1150,
    meltsTo: ElementId.Lava
  }),
  [ElementId.Glass]: def({
    id: ElementId.Glass,
    key: "glass",
    symbol: "GLAS",
    name: "玻璃",
    category: "solid",
    state: "solid",
    color: "#91d6e8",
    density: 2500,
    heatCapacity: 3.5,
    conductivity: 0.08,
    acidResistance: 0.95,
    meltPoint: 1420,
    meltsTo: ElementId.Lava
  }),
  [ElementId.Wood]: def({
    id: ElementId.Wood,
    key: "wood",
    symbol: "WOOD",
    name: "木头",
    category: "solid",
    state: "solid",
    color: "#8c5a2b",
    density: 700,
    heatCapacity: 3.2,
    conductivity: 0.05,
    acidResistance: 0.42,
    combustible: true,
    burnTemp: 280
  }),
  [ElementId.Ice]: def({
    id: ElementId.Ice,
    key: "ice",
    symbol: "ICE",
    formula: "H2O",
    name: "冰",
    category: "solid",
    state: "solid",
    color: "#bdefff",
    density: 920,
    heatCapacity: 2.2,
    conductivity: 0.16,
    acidResistance: 0.7,
    meltPoint: 1,
    meltsTo: ElementId.Water,
    defaultTemp: -8
  }),
  [ElementId.Metal]: def({
    id: ElementId.Metal,
    key: "metal",
    symbol: "METL",
    name: "金属",
    category: "electronic",
    state: "solid",
    color: "#b6bdc6",
    density: 7800,
    heatCapacity: 2.5,
    conductivity: 0.72,
    acidResistance: 0.55,
    conductive: true,
    meltPoint: 1450,
    meltsTo: ElementId.Lava
  }),
  [ElementId.Copper]: def({
    id: ElementId.Copper,
    key: "copper",
    symbol: "COPR",
    formula: "Cu",
    name: "铜",
    category: "electronic",
    state: "solid",
    color: "#d98242",
    density: 8960,
    heatCapacity: 2.3,
    conductivity: 0.9,
    acidResistance: 0.62,
    conductive: true,
    meltPoint: 1085,
    meltsTo: ElementId.Lava
  }),
  [ElementId.Gold]: def({
    id: ElementId.Gold,
    key: "gold",
    symbol: "GOLD",
    formula: "Au",
    name: "金",
    category: "electronic",
    state: "solid",
    color: "#f2c94c",
    density: 19300,
    heatCapacity: 2.1,
    conductivity: 0.86,
    acidResistance: 0.99,
    conductive: true,
    meltPoint: 1064,
    meltsTo: ElementId.Lava
  }),
  [ElementId.Wire]: def({
    id: ElementId.Wire,
    key: "wire",
    symbol: "WIRE",
    name: "导线",
    category: "electronic",
    state: "solid",
    color: "#3fc1ff",
    density: 5600,
    heatCapacity: 2.2,
    conductivity: 0.82,
    acidResistance: 0.5,
    conductive: true,
    meltPoint: 980,
    meltsTo: ElementId.Lava
  }),
  [ElementId.Battery]: def({
    id: ElementId.Battery,
    key: "battery",
    symbol: "BTRY",
    name: "电池",
    category: "electronic",
    state: "solid",
    color: "#64ff9a",
    density: 6000,
    heatCapacity: 3,
    conductivity: 0.65,
    acidResistance: 0.72,
    conductive: true,
    meltPoint: 900,
    meltsTo: ElementId.Lava
  }),
  [ElementId.Semiconductor]: def({
    id: ElementId.Semiconductor,
    key: "semiconductor",
    symbol: "SILC",
    formula: "Si",
    name: "半导体",
    category: "electronic",
    state: "solid",
    color: "#5c657c",
    density: 2330,
    heatCapacity: 2.8,
    conductivity: 0.28,
    acidResistance: 0.76,
    conductive: true,
    meltPoint: 1414,
    meltsTo: ElementId.Lava
  }),
  [ElementId.Sand]: def({
    id: ElementId.Sand,
    key: "sand",
    symbol: "SAND",
    name: "沙",
    category: "powder",
    state: "powder",
    color: "#d7b565",
    density: 1600,
    heatCapacity: 3,
    conductivity: 0.12,
    acidResistance: 0.78,
    meltPoint: 1450,
    meltsTo: ElementId.Glass
  }),
  [ElementId.Dust]: def({
    id: ElementId.Dust,
    key: "dust",
    symbol: "DUST",
    name: "尘",
    category: "powder",
    state: "powder",
    color: "#b8aa8f",
    density: 900,
    heatCapacity: 2.6,
    conductivity: 0.06,
    acidResistance: 0.45,
    combustible: true,
    burnTemp: 340
  }),
  [ElementId.Salt]: def({
    id: ElementId.Salt,
    key: "salt",
    symbol: "SALT",
    formula: "NaCl",
    name: "盐",
    category: "powder",
    state: "powder",
    color: "#ece6d4",
    density: 2160,
    heatCapacity: 3.1,
    conductivity: 0.12,
    acidResistance: 0.72,
    meltPoint: 800,
    meltsTo: ElementId.Lava
  }),
  [ElementId.Coal]: def({
    id: ElementId.Coal,
    key: "coal",
    symbol: "COAL",
    formula: "C",
    name: "煤",
    category: "powder",
    state: "powder",
    color: "#2d2b2a",
    density: 1350,
    heatCapacity: 3,
    conductivity: 0.08,
    acidResistance: 0.65,
    combustible: true,
    burnTemp: 380
  }),
  [ElementId.Clay]: def({
    id: ElementId.Clay,
    key: "clay",
    symbol: "CLST",
    name: "粘土",
    category: "powder",
    state: "powder",
    color: "#b2774f",
    density: 1700,
    heatCapacity: 3.6,
    conductivity: 0.11,
    acidResistance: 0.68,
    meltPoint: 1050,
    meltsTo: ElementId.Stone
  }),
  [ElementId.Water]: def({
    id: ElementId.Water,
    key: "water",
    symbol: "WATR",
    formula: "H2O",
    name: "水",
    category: "liquid",
    state: "liquid",
    color: "#3aa7ff",
    density: 1000,
    heatCapacity: 4.2,
    conductivity: 0.18,
    acidResistance: 0.7,
    viscosity: 4,
    boilPoint: 100,
    boilsTo: ElementId.Steam,
    freezePoint: 0,
    freezesTo: ElementId.Ice
  }),
  [ElementId.SaltWater]: def({
    id: ElementId.SaltWater,
    key: "salt-water",
    symbol: "SLTW",
    formula: "NaCl+H2O",
    name: "盐水",
    category: "liquid",
    state: "liquid",
    color: "#69bfff",
    density: 1120,
    heatCapacity: 4,
    conductivity: 0.34,
    acidResistance: 0.74,
    conductive: true,
    viscosity: 3,
    boilPoint: 108,
    boilsTo: ElementId.Steam,
    freezePoint: -8,
    freezesTo: ElementId.Ice
  }),
  [ElementId.Oil]: def({
    id: ElementId.Oil,
    key: "oil",
    symbol: "OIL",
    name: "油",
    category: "liquid",
    state: "liquid",
    color: "#6b4c23",
    density: 820,
    heatCapacity: 2.1,
    conductivity: 0.05,
    acidResistance: 0.52,
    viscosity: 3,
    combustible: true,
    burnTemp: 260,
    boilPoint: 360,
    boilsTo: ElementId.Smoke
  }),
  [ElementId.Acid]: def({
    id: ElementId.Acid,
    key: "acid",
    symbol: "ACID",
    name: "酸",
    category: "liquid",
    state: "liquid",
    color: "#85ff4b",
    density: 1220,
    heatCapacity: 3.3,
    conductivity: 0.26,
    acidResistance: 1,
    viscosity: 3,
    boilPoint: 120,
    boilsTo: ElementId.Steam
  }),
  [ElementId.Base]: def({
    id: ElementId.Base,
    key: "base",
    symbol: "BASE",
    name: "碱",
    category: "liquid",
    state: "liquid",
    color: "#b2ff7a",
    density: 1180,
    heatCapacity: 4.8,
    conductivity: 0.22,
    acidResistance: 1,
    viscosity: 3,
    boilPoint: 130,
    boilsTo: ElementId.Steam
  }),
  [ElementId.Lava]: def({
    id: ElementId.Lava,
    key: "lava",
    symbol: "LAVA",
    name: "熔岩",
    category: "liquid",
    state: "liquid",
    color: "#ff6b21",
    density: 3100,
    heatCapacity: 4.4,
    conductivity: 0.38,
    acidResistance: 0.95,
    viscosity: 1,
    defaultTemp: 980,
    coolsTo: ElementId.Stone
  }),
  [ElementId.LiquidNitrogen]: def({
    id: ElementId.LiquidNitrogen,
    key: "liquid-nitrogen",
    symbol: "LN2",
    formula: "N2",
    name: "液氮",
    category: "liquid",
    state: "liquid",
    color: "#d7fbff",
    density: 808,
    heatCapacity: 2,
    conductivity: 0.16,
    acidResistance: 0.8,
    viscosity: 5,
    defaultTemp: -196,
    boilPoint: -160,
    boilsTo: ElementId.Smoke
  }),
  [ElementId.Mercury]: def({
    id: ElementId.Mercury,
    key: "mercury",
    symbol: "MERC",
    formula: "Hg",
    name: "水银",
    category: "liquid",
    state: "liquid",
    color: "#d8dde5",
    density: 13546,
    heatCapacity: 1.5,
    conductivity: 0.46,
    acidResistance: 0.78,
    conductive: true,
    viscosity: 2,
    freezePoint: -39,
    freezesTo: ElementId.Metal
  }),
  [ElementId.Steam]: def({
    id: ElementId.Steam,
    key: "steam",
    symbol: "STEM",
    formula: "H2O",
    name: "蒸汽",
    category: "gas",
    state: "gas",
    color: "#d5e9f0",
    density: 35,
    heatCapacity: 2.1,
    conductivity: 0.08,
    acidResistance: 0.8,
    condensesTo: ElementId.Water,
    defaultTemp: 118
  }),
  [ElementId.Smoke]: def({
    id: ElementId.Smoke,
    key: "smoke",
    symbol: "SMKE",
    name: "烟",
    category: "gas",
    state: "gas",
    color: "#65656a",
    density: 24,
    heatCapacity: 1.2,
    conductivity: 0.04,
    acidResistance: 0.9,
    defaultTemp: 75
  }),
  [ElementId.Hydrogen]: def({
    id: ElementId.Hydrogen,
    key: "hydrogen",
    symbol: "HYGN",
    formula: "H2",
    name: "氢气",
    category: "gas",
    state: "gas",
    color: "#ffe9a6",
    density: 6,
    heatCapacity: 14,
    conductivity: 0.18,
    acidResistance: 0.95,
    combustible: true,
    burnTemp: 220,
    defaultTemp: 22
  }),
  [ElementId.Oxygen]: def({
    id: ElementId.Oxygen,
    key: "oxygen",
    symbol: "OXYG",
    formula: "O2",
    name: "氧气",
    category: "gas",
    state: "gas",
    color: "#a9d8ff",
    density: 12,
    heatCapacity: 1,
    conductivity: 0.07,
    acidResistance: 0.96
  }),
  [ElementId.Fire]: def({
    id: ElementId.Fire,
    key: "fire",
    symbol: "FIRE",
    name: "火",
    category: "gas",
    state: "energy",
    color: "#ffcf45",
    density: 4,
    heatCapacity: 0.5,
    conductivity: 0.25,
    acidResistance: 1,
    defaultTemp: 620
  }),
  [ElementId.Plasma]: def({
    id: ElementId.Plasma,
    key: "plasma",
    symbol: "PLSM",
    name: "等离子",
    category: "gas",
    state: "energy",
    color: "#a75cff",
    density: 2,
    heatCapacity: 0.25,
    conductivity: 0.55,
    acidResistance: 1,
    defaultTemp: 2600
  }),
  [ElementId.Spark]: def({
    id: ElementId.Spark,
    key: "spark",
    symbol: "SPRK",
    name: "火花",
    category: "electronic",
    state: "energy",
    color: "#e9faff",
    density: 1,
    heatCapacity: 0.1,
    conductivity: 1,
    acidResistance: 1,
    defaultTemp: 380
  }),
  [ElementId.Plant]: def({
    id: ElementId.Plant,
    key: "plant",
    symbol: "PLNT",
    name: "植物",
    category: "life",
    state: "solid",
    color: "#34c759",
    density: 650,
    heatCapacity: 3.8,
    conductivity: 0.07,
    acidResistance: 0.38,
    combustible: true,
    burnTemp: 220
  }),
  [ElementId.Seed]: def({
    id: ElementId.Seed,
    key: "seed",
    symbol: "SEED",
    name: "种子",
    category: "life",
    state: "powder",
    color: "#7b4f2a",
    density: 740,
    heatCapacity: 3.1,
    conductivity: 0.06,
    acidResistance: 0.42,
    combustible: true,
    burnTemp: 210
  }),
  [ElementId.Uranium]: def({
    id: ElementId.Uranium,
    key: "uranium",
    symbol: "URAN",
    formula: "U",
    name: "铀",
    category: "nuclear",
    state: "powder",
    color: "#79ff79",
    density: 19050,
    heatCapacity: 2.2,
    conductivity: 0.24,
    acidResistance: 0.64,
    meltPoint: 1132,
    meltsTo: ElementId.Lava
  }),
  [ElementId.Neutron]: def({
    id: ElementId.Neutron,
    key: "neutron",
    symbol: "NEUT",
    name: "中子",
    category: "nuclear",
    state: "energy",
    color: "#d8ffef",
    density: 1,
    heatCapacity: 0.1,
    conductivity: 0.1,
    acidResistance: 1
  }),
  [ElementId.Photon]: def({
    id: ElementId.Photon,
    key: "photon",
    symbol: "PHOT",
    name: "光子",
    category: "nuclear",
    state: "energy",
    color: "#fff7bf",
    density: 1,
    heatCapacity: 0.1,
    conductivity: 0.1,
    acidResistance: 1
  }),
  [ElementId.BlackHole]: def({
    id: ElementId.BlackHole,
    key: "black-hole",
    symbol: "BHOL",
    name: "黑洞",
    category: "nuclear",
    state: "solid",
    color: "#020205",
    density: 99999,
    heatCapacity: 99,
    conductivity: 1,
    acidResistance: 1,
    immovable: true
  })
};

export const CATEGORY_LABELS: Record<ElementCategory, string> = {
  powder: "粉末",
  liquid: "液体",
  gas: "气体/能量",
  solid: "固体",
  electronic: "电学",
  nuclear: "高能",
  life: "生命"
};

export const ELEMENT_ORDER: ElementId[] = [
  ElementId.Sand,
  ElementId.Dust,
  ElementId.Salt,
  ElementId.Coal,
  ElementId.Clay,
  ElementId.Water,
  ElementId.SaltWater,
  ElementId.Oil,
  ElementId.Acid,
  ElementId.Base,
  ElementId.Lava,
  ElementId.LiquidNitrogen,
  ElementId.Mercury,
  ElementId.Steam,
  ElementId.Smoke,
  ElementId.Hydrogen,
  ElementId.Oxygen,
  ElementId.Fire,
  ElementId.Plasma,
  ElementId.Wall,
  ElementId.Stone,
  ElementId.Glass,
  ElementId.Ice,
  ElementId.Wood,
  ElementId.Metal,
  ElementId.Copper,
  ElementId.Gold,
  ElementId.Wire,
  ElementId.Battery,
  ElementId.Semiconductor,
  ElementId.Spark,
  ElementId.Plant,
  ElementId.Seed,
  ElementId.Uranium,
  ElementId.Neutron,
  ElementId.Photon,
  ElementId.BlackHole
];

export const TOOLS: Array<{ id: ToolId; symbol: string; name: string; description: string }> = [
  { id: "ERASE", symbol: "ERAS", name: "擦除", description: "清空粒子" },
  { id: "HEAT", symbol: "HEAT", name: "加热", description: "提高温度" },
  { id: "COOL", symbol: "COOL", name: "冷却", description: "降低温度" },
  { id: "WIND", symbol: "WIND", name: "风", description: "写入局部速度场" },
  { id: "VAC", symbol: "VAC", name: "真空", description: "降低局部压力" },
  { id: "PRES", symbol: "PRES", name: "压力", description: "提高局部压力" },
  { id: "MIX", symbol: "MIX", name: "搅拌", description: "打散局部粒子" }
];

export const elementLabel = (id: ElementId): string => {
  const element = ELEMENTS[id];
  return `${element.name}(${element.formula ? `${element.formula}/${element.symbol}` : element.symbol})`;
};

export const isConductive = (id: ElementId): boolean => Boolean(ELEMENTS[id]?.conductive);
